### ISSUE TITLE
Enable branch protection on `main`

### ISSUE THREAD

**Issue by lobsterkatie** [getsentry/rfcs#17]
I just boneheadedly forgot the `-b` when checking out a new branch, didn't notice git's refusal to check out a branch which didn't yet exist, committed to `main`, and pushed. Whoops.

I'm generally not in favor of locking things down any more than necessary, but disallowing such shenanigans, however accidental, feels like a good saving-us-from-ourselves move.

**Comment by mitsuhiko** [comment]
Done
