### ISSUE TITLE
[DECISION] Add RFC for top level span creation method

### ISSUE THREAD

**Issue by AbhiPrasad** [getsentry/rfcs#28]
ref:
- https://github.com/getsentry/sentry-laravel/pull/598
- https://github.com/getsentry/sentry-java/issues/1154

- https://github.com/getsentry/sentry-javascript/pull/3753

Introduce a `Sentry.trace` method that wraps a callback with a created span.

**Comment by sl0thentr0py** [comment]
in ruby we just added 
https://github.com/getsentry/sentry-ruby/pull/1783
we can rename in a major for consistency if this becomes unified API

**Comment by AbhiPrasad** [comment]
Wrote out why this is need for OpenTelemetry here: https://github.com/getsentry/develop/issues/720
